### ISSUE TITLE
Fix time type error with dom lib compiler options 

### ISSUE THREAD

**Issue by KyleJune** [udibo/mock#28]
When using dom compiler options, the type of the first argument is TimerHandler. When overriding the setTimeout and setInterval functions on globalThis, it gets a type error. TimerHandler is an alias for Function | string, but the timer only allows a callback as the first argument. The string input is not recommended or implemented in Deno, so I did not implement it in this library either. 

https://developer.mozilla.org/en-US/docs/Web/API/setTimeout

Here are the type errors that would occur when importing this module into one that uses dom compiler options.

```
error: TS2322 [ERROR]: Type '(callback: (...args: any[]) => void, delay?: number, ...args: any[]) => number' is not assignable to type '(handler: TimerHandler, timeout?: number | undefined, ...arguments: any[]) => number'.
  Types of parameters 'callback' and 'handler' are incompatible.
    Type 'TimerHandler' is not assignable to type '(...args: any[]) => void'.
      Type 'string' is not assignable to type '(...args: any[]) => void'.
    globalThis.setTimeout = FakeTime.setTimeout;
    ~~~~~~~~~~~~~~~~~~~~~
    at file:///home/kyle/Projects/deno/mock/time.ts:271:5

TS2322 [ERROR]: Type '(callback: (...args: any[]) => unknown, delay?: number, ...args: any[]) => number' is not assignable to type '(handler: TimerHandler, timeout?: number | undefined, ...arguments: any[]) => number'.
  Types of parameters 'callback' and 'handler' are incompatible.
    Type 'TimerHandler' is not assignable to type '(...args: any[]) => unknown'.
      Type 'string' is not assignable to type '(...args: any[]) => unknown'.
    globalThis.setInterval = FakeTime.setInterval;
    ~~~~~~~~~~~~~~~~~~~~~~
    at file:///home/kyle/Projects/deno/mock/time.ts:273:5
```

**Comment by KyleJune** [comment]
Fixed by https://github.com/udibo/mock/commit/5bdbbf6dc8881cb4edae90acbfd5993a52564cf1
